# Site settings
title: Bohee :)
email: bohee.lee89@gmail.com
url: https://example.github.io
description: "Hi there, this is Bohee! My interest is in brain science and technology. "I'd love to share my knowledge and experience with you, so don't hesitate to contact me for those topics or just for chitchats!

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Bohee's Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/bohee-lee
  - title: facebook
    url: https://facebook.com/dasase012
  - title: github
    url: https://github.com/dasase012

# Build settings
markdown: kramdown
permalink: pretty
